query LIST_OF_EVENTS {
  events {
    creator {
      _id
      email
      password
      createdEvents {
        _id
        title
        description
        date
      }
    }
  }
}

mutation CREATING_EVENT(
  $title: String!
  $description: String!
  $price: Float!
  $date: String!
) {
  createEvent(
    eventInput: {
      title: $title
      description: $description
      price: $price
      date: $date
    }
  ) {
    _id
    title
    description
    price
    date
  }
}
